 
name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unitTests:
    strategy:
      matrix:
        name: [ubuntu-gcc, ubuntu-clang, windows-VS]
        include:
            - name: ubuntu-gcc
              install_omp: 'Yes'
              os: ubuntu-latest
              compiler_opt: "-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -G \"Unix Makefiles\""
            - name: ubuntu-clang
              install_omp: 'Yes'
              os: ubuntu-latest
              compiler_opt: "-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G \"Unix Makefiles\""
            - name: windows-VS
              install_omp: 'No'
              os: windows-latest
              compiler_opt: ""

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Checkout submodules
      run:  git submodule update --init --recursive
    - name: Install openMP
      if: matrix.install_omp == 'Yes'
      run:  sudo apt install libomp-dev
    - name: CMake configure
      run: cmake -B./build -DCMAKE_INSTALL_PREFIX:STRING=./artifacts/ -DBUILD_DYN_FLOW_SAMPLES=OFF -DBUILD_DYN_FLOW_TESTS=ON -DCMAKE_CONFIGURATION_TYPES="Release" -DCMAKE_BUILD_TYPE:STRING=Release ${{ matrix.compiler_opt }}     
    - name: Build
      run:  cmake --build ./build --config Release
    - name: Install
      run:  cmake --install ./build --config Release
    - name: Tests
      run: ./artifacts/bin/DynamicFlowTests
    - uses: actions/upload-artifact@v4.4.1
      with:
        path: artifacts
        name: ${{ matrix.name }}
